# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'facebookAPI' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for facebookAPI
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'

  # Pod for JSON serialization / deserilization
  #pod 'JSONModel'

  # Swift 3.0 pod for JSON serialization / deserialization
  #pod 'SwiftyJSON'

  #AFNetworking reloaded in swift
  pod 'Alamofire', '~> 4.4'

  #JSON to Swift Model Object Mapping, 
  pod 'ObjectMapper', '~> 2.2'

  #Alamofire + ObjectMapper
  #pod 'AlamofireObjectMapper', '~> 4.0'

  #Coredata helper - SugarRecord
  pod "SugarRecord/CoreData"
  
  #Swinject
  #pod 'Swinject', '~> 2.0.0'

end
